export const projects = [
    {
      name: 'Castle Journal',
      weblink: 'https://rocky-fortress-11303.herokuapp.com',
      gitlink: 'https://github.com/tcunningham203/100-famous-castles',
      pic: '/react-portfolio/images/thumb1.png',
      about: 'Discover Japanese castles and collect stamps.',
      about2: 'MVC structure, Bootstrap, Express, and Handlebars.',
    },
    {
      name: 'PokéWiki',
      weblink: 'https://tcunningham203.github.io/Etsy-Pokedex',
      gitlink: 'https://github.com/tcunningham203/Etsy-Pokedex',
      pic: '/react-portfolio/images/thumb2.png',
      about: 'Pokémon search engine with a Pokédex style UI.',
      about2: 'Uses PokéAPI, Wikipedia API, and Materialize CSS.',
    },
    {
      name: 'Tim\'s Tech Blog',
      weblink: 'https://safe-thicket-86598-f51cd826f717.herokuapp.com',
      gitlink: 'https://github.com/tcunningham203/MVC-Tech-Blog',
      pic: '/react-portfolio/images/thumb3.png',
      about: 'View, create, update, delete and comment on posts.',
      about2: 'MVC structure, Bootstrap, Express, and Handlebars.',
    },
    {
      name: 'Weather Dashboard',
      weblink: 'https://tcunningham203.github.io/tim-weather-dashboard',
      gitlink: 'https://github.com/tcunningham203/tim-weather-dashboard',
      pic: '/react-portfolio/images/thumb4.png',
      about: 'Get a city\'s forecast using Open Weather Map API.', 
      about2: 'Save recent searches in local storage.',
    },
    {
      name: 'Employee Tracker',
      weblink: 'https://github.com/tcunningham203/SQL-Employee-Tracker',
      gitlink: 'https://github.com/tcunningham203/SQL-Employee-Tracker',
      pic: '/react-portfolio/images/thumb5.png',
      about: 'Manage employees with this command line app.',
      about2: 'Uses Node.js, Inquirer, and MySQL.',
    },
    {
      name: 'Work Day Scheduler',
      weblink: 'https://tcunningham203.github.io/tim-work-day-scheduler',
      gitlink: 'https://github.com/tcunningham203/tim-work-day-scheduler',
      pic: '/react-portfolio/images/thumb6.png',
      about: 'Save hourly events with this basic calendar app.',
      about2: 'Created with jQuery and DayJS.',
    },
  ];